api_platform:
    title: API Platform - MonCentrePermis
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        #pagination_enabled: false
    collection:
        pagination:
            enabled_parameter_name: pagination 

