security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Compte
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    media:
      pattern: ^/media
      stateless: true
      provider: app_user_provider
      jwt: ~

    # Configuration principale pour les routes sécurisées par JWT
    main:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /api/login
        success_handler: App\Security\JWTAuthenticationSuccessHandler
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

      # Gestion de l'authentification avec le bundle JWT
      jwt: ~

      #logout:
      #path: /api/logout
      #invalidate_session: false

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/custom/centre_examens, roles: PUBLIC_ACCESS }
    - { path: ^/api/compte/create-compte, roles: PUBLIC_ACCESS }
    - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
    - { path: ^/api/moniteurs/mycourses, roles: IS_AUTHENTICATED_FULLY } # Permet l'accès à tous les utilisateurs authentifiés
    - { path: ^/api/logout, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/media, roles: IS_AUTHENTICATED_FULLY }
